[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "table.sort(card_protos, function (a, b) return "
position = "before"
payload = '''
if self.GAME.starting_params.minimalistic then
    for _ = 1, #card_protos / 2 do
        local card_idx = pseudorandom("minimalistic_deck", 1, #card_protos);
        table.remove(card_protos, card_idx);
    end
end

'''
match_indent = true