[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "erratic_suits_and_ranks = false,"
position = "after"
payload = '''
minimalistic = false,
'''
match_indent = true