[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "=[SMODS _ \"src/utils.lua\"]"
pattern = """
if scoring_hand and card.debuff then
    if in_scoring then
"""
position = "after"
payload = '''
jon_handle_debuffed_card()
'''
match_indent = true
